=== ChrL73/Diaphnea/Quiz/VisualStudio/QuestionInstantiation/XmlQuizData.xsd
<?xml version="1.0" encoding="utf-8" ?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
  <xsd:element name="quizData" type="XmlQuizData" />
  <xsd:complexType name="XmlQuizData">
    <xsd:sequence>
      <xsd:element name="typeDefinitions" type="XmlTypeDefinition" maxOccurs="1" minOccurs="1" />
      <xsd:element name="levelList" type="XmlLevelList" maxOccurs="1" minOccurs="1" />
      <xsd:element name="elementList" type="XmlElementList" maxOccurs="1" minOccurs="1" />
      <xsd:element name="questionCategories" type="XmlQuestionCategories" maxOccurs="1" minOccurs="1" />
    </xsd:sequence>
  </xsd:complexType>
  <xsd:complexType name="XmlTypeDefinition">
    <xsd:sequence>
      <xsd:element name="elementTypeList" type="XmlElementTypeList" maxOccurs="1" minOccurs="1" />
      <xsd:element name="attributeTypeList" type="XmlAttributeTypeList" maxOccurs="1" minOccurs="1" />
      <xsd:element name="numericalAttributeTypeList" type="XmlNumericalAttributeTypeList" maxOccurs="1" minOccurs="1" />
      <xsd:element name="relation11TypeList" type="XmlRelation11TypeList" maxOccurs="1" minOccurs="1" />
      <xsd:element name="relation1NTypeList" type="XmlRelation1NTypeList" maxOccurs="1" minOccurs="1" />
      <xsd:element name="relationNNTypeList" type="XmlRelationNNTypeList" maxOccurs="1" minOccurs="1" />
    </xsd:sequence>
  </xsd:complexType>
  <xsd:complexType name="XmlElementTypeList">
    <xsd:sequence>
      <xsd:element name="elementType" type="XmlElementType" minOccurs="1" maxOccurs="unbounded" />
    </xsd:sequence>
  </xsd:complexType>
  <xsd:complexType name="XmlElementType">
    <xsd:sequence />
    <xsd:attribute name="id" type="XmlElementTypeId" use="required" />
  </xsd:complexType>
  <xsd:simpleType name="XmlElementTypeId">
    <xsd:restriction base="xsd:ID">
      <xsd:pattern value="et_(.)+" />
    </xsd:restriction>
  </xsd:simpleType>
  <xsd:complexType name="XmlAttributeTypeList">
    <xsd:sequence>
      <xsd:element name="attributeType" type="XmlAttributeType" minOccurs="1" maxOccurs="unbounded" />
    </xsd:sequence>
  </xsd:complexType>
  <xsd:complexType name="XmlAttributeType">
    <xsd:sequence></xsd:sequence>
    <xsd:attribute name="id" type="XmlAttributeTypeId" use="required" />
    <xsd:attribute name="canBeQuestion" type="xsd:boolean" use="required" />
  </xsd:complexType>
  <xsd:simpleType name="XmlAttributeTypeId">
    <xsd:restriction base="xsd:ID">
      <xsd:pattern value="at_(.)+" />
    </xsd:restriction>
  </xsd:simpleType>
  <xsd:complexType name="XmlNumericalAttributeTypeList">
    <xsd:sequence>
      <xsd:element name="numericalAttributeType" type="XmlNumericalAttributeType" minOccurs="1" maxOccurs="unbounded" />
    </xsd:sequence>
  </xsd:complexType>
  <xsd:complexType name="XmlNumericalAttributeType">
    <xsd:sequence></xsd:sequence>
    <xsd:attribute name="id" type="XmlNumericalAttributeTypeId" use="required" />
    <xsd:attribute name="unit" type="xsd:string" use="required" />
    <xsd:attribute name="ambiguityThreshold" type="XmlPositiveDouble" use="required" />
    <xsd:attribute name="displayPrecision" type="XmlPrecision" use="required" />
  </xsd:complexType>
  <xsd:simpleType name="XmlNumericalAttributeTypeId">
    <xsd:restriction base="xsd:ID">
      <xsd:pattern value="nt_(.)+" />
    </xsd:restriction>
  </xsd:simpleType>
  <xsd:simpleType name="XmlPositiveDouble">
    <xsd:restriction base="xsd:double">
      <xsd:minExclusive value="0" />
    </xsd:restriction>
  </xsd:simpleType>
  <xsd:simpleType name="XmlPrecision">
    <xsd:restriction base="xsd:nonNegativeInteger">
      <xsd:maxInclusive value="9" />
    </xsd:restriction>
  </xsd:simpleType>
  <xsd:complexType name="XmlRelation11TypeList">
    <xsd:sequence>
      <xsd:element name="relation11Type" type="XmlRelation11Type" minOccurs="0" maxOccurs="unbounded" />
    </xsd:sequence>
  </xsd:complexType>
  <xsd:complexType name="XmlRelation11Type">
    <xsd:sequence></xsd:sequence>
    <xsd:attribute name="id" type="XmlRelation11TypeId" use="required" />
    <xsd:attribute name="startType" type="XmlElementTypeIdRef" use="required" />
    <xsd:attribute name="endType" type="XmlElementTypeIdRef" use="required" />
  </xsd:complexType>
  <xsd:simpleType name="XmlRelation11TypeId">
    <xsd:restriction base="xsd:ID">
      <xsd:pattern value="r11_(.)+" />
    </xsd:restriction>
  </xsd:simpleType>
  <xsd:simpleType name="XmlElementTypeIdRef">
    <xsd:restriction base="xsd:IDREF">
      <xsd:pattern value="et_(.)+" />
    </xsd:restriction>
  </xsd:simpleType>
  <xsd:complexType name="XmlRelation1NTypeList">
    <xsd:sequence>
      <xsd:element name="relation1NType" type="XmlRelation1NType" minOccurs="0" maxOccurs="unbounded" />
    </xsd:sequence>
  </xsd:complexType>
  <xsd:complexType name="XmlRelation1NType">
    <xsd:sequence></xsd:sequence>
    <xsd:attribute name="id" type="Relation1NTypeId" use="required" />
    <xsd:attribute name="startType" type="XmlElementTypeIdRef" use="required" />
    <xsd:attribute name="endType" type="XmlElementTypeIdRef" use="required" />
  </xsd:complexType>
  <xsd:simpleType name="Relation1NTypeId">
    <xsd:restriction base="xsd:ID">
      <xsd:pattern value="r1N_(.)+" />
    </xsd:restriction>
  </xsd:simpleType>
  <xsd:complexType name="XmlRelationNNTypeList">
    <xsd:sequence>
      <xsd:element name="relationNNType" type="XmlRelationNNType" minOccurs="0" maxOccurs="unbounded" />
    </xsd:sequence>
  </xsd:complexType>
  <xsd:complexType name="XmlRelationNNType">
    <xsd:sequence></xsd:sequence>
    <xsd:attribute name="id" type="XmlRelationNNTypeId" use="required" />
    <xsd:attribute name="startType" type="XmlElementTypeIdRef" use="required" />
    <xsd:attribute name="endType" type="XmlElementTypeIdRef" use="required" />
    <xsd:attribute name="checkSymetry" type="XmlCheckSymetryEnum" use="optional" />
  </xsd:complexType>
  <xsd:simpleType name="XmlRelationNNTypeId">
    <xsd:restriction base="xsd:ID">
      <xsd:pattern value="rNN_(.)+" />
    </xsd:restriction>
  </xsd:simpleType>
  <xsd:simpleType name="XmlCheckSymetryEnum">
    <xsd:restriction base="xsd:string">
      <xsd:enumeration value="no" />
      <xsd:enumeration value="yesWarning" />
      <xsd:enumeration value="yesError" />
    </xsd:restriction>
  </xsd:simpleType>
  <xsd:complexType name="XmlLevelList">
    <xsd:sequence>
      <xsd:element name="level" type="XmlLevel" maxOccurs="unbounded" minOccurs="1" />
    </xsd:sequence>
  </xsd:complexType>
  <xsd:complexType name="XmlLevel">
    <xsd:attribute name="value" type="xsd:nonNegativeInteger" use="required" />
    <xsd:attribute name="name" type="xsd:string" use="required" />
    <xsd:attribute name="choiceCount" type="xsd:positiveInteger" use="required" />
    <xsd:attribute name="questionCount" type="xsd:positiveInteger" use="required" />
    <xsd:attribute name="distribParameter" type="XmlDistribParameter" use="required" />
  </xsd:complexType>
  <xsd:simpleType name="XmlDistribParameter">
    <xsd:restriction base="xsd:double">
      <xsd:minInclusive value="0" />
      <xsd:maxInclusive value="1" />
    </xsd:restriction>
  </xsd:simpleType>
  <xsd:complexType name="XmlElementList">
    <xsd:sequence>
      <xsd:element name="element" type="XmlElement" minOccurs="1" maxOccurs="unbounded" />
    </xsd:sequence>
  </xsd:complexType>
  <xsd:complexType name="XmlElement">
    <xsd:sequence>
      <xsd:element name="attributeList" type="XmlAttributeList" maxOccurs="1" minOccurs="1" />
      <xsd:element name="numericalAttributeList" type="XmlNumericalAttributeList" maxOccurs="1" minOccurs="1" />
      <xsd:element name="relationList" type="XmlRelationList" maxOccurs="1" minOccurs="1" />
    </xsd:sequence>
    <xsd:attribute name="id" type="XmlElementId" use="required" />
    <xsd:attribute name="name" type="xsd:string" use="required" />
    <xsd:attribute name="type" type="XmlElementTypeIdRef" use="required" />
    <xsd:attribute name="minLevel" type="xsd:nonNegativeInteger" use="required" />
    <xsd:attribute name="mapLevel" type="xsd:unsignedByte" use="required" />
    <xsd:attribute name="sortKey" type="xsd:string" use="optional" />
  </xsd:complexType>
  <xsd:complexType name="XmlAttributeList">
    <xsd:sequence>
      <xsd:element name="attribute" type="XmlAttribute" minOccurs="0" maxOccurs="unbounded" />
    </xsd:sequence>
  </xsd:complexType>
  <xsd:complexType name="XmlNumericalAttributeList">
    <xsd:sequence>
      <xsd:element name="numericalAttribute" type="XmlNumericalAttribute" minOccurs="0" maxOccurs="unbounded" />
    </xsd:sequence>
  </xsd:complexType>
  <xsd:complexType name="XmlRelationList">
    <xsd:sequence>
      <xsd:element name="relation" type="XmlRelation" minOccurs="0" maxOccurs="unbounded" />
    </xsd:sequence>
  </xsd:complexType>
  <xsd:complexType name="XmlAttribute">
    <xsd:sequence></xsd:sequence>
    <xsd:attribute name="type" type="XmlAttributeTypeIdRef" use="required" />
    <xsd:attribute name="value" type="xsd:string" use="required" />
    <xsd:attribute name="comment" type="xsd:string" use="optional" />
  </xsd:complexType>
  <xsd:complexType name="XmlNumericalAttribute">
    <xsd:sequence></xsd:sequence>
    <xsd:attribute name="type" type="XmlNumericalAttributeTypeIdRef" use="required" />
    <xsd:attribute name="value" type="xsd:double" use="required" />
  </xsd:complexType>
  <xsd:simpleType name="XmlElementId">
    <xsd:restriction base="xsd:ID">
      <xsd:pattern value="el_(.)+" />
    </xsd:restriction>
  </xsd:simpleType>
  <xsd:complexType name="XmlRelation">
    <xsd:sequence />
    <xsd:attribute name="type" type="XmlRelationIdRef" use="required" />
    <xsd:attribute name="linkedElement" type="XmlElementIdRef" use="required" />
  </xsd:complexType>
  <xsd:simpleType name="XmlAttributeTypeIdRef">
    <xsd:restriction base="xsd:IDREF">
      <xsd:pattern value="at_(.)+" />
    </xsd:restriction>
  </xsd:simpleType>
  <xsd:simpleType name="XmlNumericalAttributeTypeIdRef">
    <xsd:restriction base="xsd:IDREF">
      <xsd:pattern value="nt_(.)+" />
    </xsd:restriction>
  </xsd:simpleType>
  <xsd:simpleType name="XmlRelationIdRef">
    <xsd:restriction base="xsd:IDREF">
      <xsd:pattern value="r.._(.)+" />
    </xsd:restriction>
  </xsd:simpleType>
  <xsd:simpleType name="XmlElementIdRef">
    <xsd:restriction base="xsd:IDREF">
      <xsd:pattern value="el_(.)+" />
    </xsd:restriction>
  </xsd:simpleType>
  <xsd:complexType name="XmlQuestionCategories">
    <xsd:sequence>
      <xsd:element name="attributeQuestionCategoryList" type="XmlAttributeQuestionCategoryList" maxOccurs="1" minOccurs="1" />
      <!--<xsd:element name="attributeOrderQuestionCategoryList" type="AttributeOrderQuestionCategoryList" maxOccurs="1" minOccurs="1" />
      <xsd:element name="relation1QuestionCategoryList" type="Relation1QuestionCategoryList" maxOccurs="1" minOccurs="1" />
      <xsd:element name="relationNQuestionCategoryList" type="RelationNQuestionCategoryList" maxOccurs="1" minOccurs="1" />
      <xsd:element name="relationLimitQuestionCategoryList" type="RelationLimitQuestionCategoryList" maxOccurs="1" minOccurs="1" />
      <xsd:element name="relationOrderQuestionCategoryList" type="RelationOrderQuestionCategoryList" maxOccurs="1" minOccurs="1" />
      <xsd:element name="relationExistenceQuestionCategoryList" type="RelationExistenceQuestionCategoryList" maxOccurs="1" minOccurs="1" />-->
    </xsd:sequence>
  </xsd:complexType>
  <xsd:complexType name="XmlAttributeQuestionCategoryList">
    <xsd:sequence>
      <xsd:element name="attributeQuestionCategory" type="XmlAttributeQuestionCategory" minOccurs="0"
				maxOccurs="unbounded" />
    </xsd:sequence>
  </xsd:complexType>
  <xsd:complexType name="XmlAttributeQuestionCategory">
    <xsd:sequence></xsd:sequence>
    <xsd:attribute name="elementType" type="XmlElementTypeIdRef" use="required" />
    <xsd:attribute name="questionAttribute" type="XmlAttributeTypeIdRef" use="required" />
    <xsd:attribute name="answerAttribute" type="XmlAttributeTypeIdRef" use="required" />
    <xsd:attribute name="answerProximityCriterion" type="XmlAnswerProximityCriterionEnum" use="required" />
    <xsd:attribute name="distribParameterCorrection" type="XmlDistribParameter" use="optional" />
    <xsd:attribute name="commentMode" type="XmlCommentModeEnum" use="required" />
    <xsd:attribute name="weight" type="xsd:nonNegativeInteger" use="required" />
    <xsd:attribute name="minLevel" type="xsd:nonNegativeInteger" use="required" />
    <xsd:attribute name="question" type="XmlString1P" use="required" />
  </xsd:complexType>
  <xsd:simpleType name="XmlAnswerProximityCriterionEnum">
    <xsd:restriction base="xsd:string">
      <xsd:enumeration value="attributeValue" />
      <xsd:enumeration value="sortKey" />
      <xsd:enumeration value="elementLocation" />
      <xsd:enumeration value="none" />
    </xsd:restriction>
  </xsd:simpleType>
  <xsd:simpleType name="XmlCommentModeEnum">
    <xsd:restriction base="xsd:string">
      <xsd:enumeration value="questionAttribute" />
      <xsd:enumeration value="name" />
      <xsd:enumeration value="none" />
    </xsd:restriction>
  </xsd:simpleType>
  <xsd:simpleType name="XmlString1P">
    <xsd:restriction base="xsd:string">
      <xsd:pattern value="[^%^#]*%[^%^#]*" />
    </xsd:restriction>
  </xsd:simpleType>
</xsd:schema>

=== ChrL73/Diaphnea/Quiz/VisualStudio/QuestionInstantiation/QuizData_Gabon.xml
<?xml version="1.0" encoding="utf-8"?>
<quizData xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="XmlQuizData.xsd">

  <parameters questionnaireId="_Gabon" logFileName="log.txt" fileLogLevel="MESSAGE" consoleLogLevel="MESSAGE" databaseName="diaphnea">
    <languageList>
      <language id="fr" name="Français" status="TRANSLATION_COMPLETED"/>
      <language id="en" name="English" status="IGNORE"/>
    </languageList>
    <questionnaireName>
      <name language="fr" text="Gabon"/>
      <name language="en" text="Gabon"/>
    </questionnaireName>
    <levelList>
      <level levelId="lv_Facile" value="0" choiceCount="4" questionCount="10" distribParameter="0.35">
        <name language="fr" text="Facile"/>
        <name language="en" text="Easy"/>
      </level>
      <level levelId="lv_Moyen" value="1" choiceCount="5" questionCount="15" distribParameter="0.2">
        <name language="fr" text="Moyen"/>
        <name language="en" text="Medium"/>
      </level>
      <level levelId="lv_Difficile" value="2" choiceCount="6" questionCount="15" distribParameter="0.1">
        <name language="fr" text="Difficile"/>
        <name language="en" text="Hard"/>
      </level>
    </levelList>
  </parameters>

  <typeDefinitions>
    <elementTypeList>
      <elementType id="et_Province" />
      <elementType id="et_Departement" />
      <elementType id="et_Ville" />
      <elementType id="et_FleuveRiviere" />
      <elementType id="et_Pays" />
    </elementTypeList>
    <attributeTypeList>
      <attributeType id="at_Nom1" canBeQuestion="true" />
      <attributeType id="at_Nom2" canBeQuestion="true" />
      <attributeType id="at_Numero" canBeQuestion="true" />
    </attributeTypeList>
    <numericalAttributeTypeList>
      <numericalAttributeType id="nt_Latitude" unit="°" ambiguityThreshold="0.4" displayPrecision="2"/>
      <numericalAttributeType id="nt_Longitude" unit="°" ambiguityThreshold="0.6" displayPrecision="2"/>
      <numericalAttributeType id="nt_Longueur" unit=" km" ambiguityThreshold="120" displayPrecision="0"/>
      <numericalAttributeType id="nt_Population" unit=" h" ambiguityThreshold="25000" displayPrecision="0"/>
    </numericalAttributeTypeList>
    <relation11TypeList>
      <relation11Type id="r11_Province_ChefLieu" startType="et_Province" endType="et_Ville" />
      <relation11Type id="r11_Departement_ChefLieu" startType="et_Departement" endType="et_Ville" />
    </relation11TypeList>
    <relation1NTypeList>
      <relation1NType id="r1N_Province_Departements" startType="et_Province" endType="et_Departement" />
      <relation1NType id="r1N_Departement_Villes" startType="et_Departement" endType="et_Ville"/>
      <relation1NType id="r1N_Riviere_Villes" startType="et_FleuveRiviere" endType="et_Ville" />
      <relation1NType id="r1N_Riviere_Affluents" startType="et_FleuveRiviere" endType="et_FleuveRiviere" />
    </relation1NTypeList>
    <relationNNTypeList>
      <relationNNType id="rNN_Riviere_Departements" startType="et_FleuveRiviere" endType="et_Departement" />
      <relationNNType id="rNN_Province_ProvincesLimitrophes" startType="et_Province" endType="et_Province" checkSymetry="YES_ERROR" />
      <relationNNType id="rNN_Departement_DepartementsLimitrophes" startType="et_Departement" endType="et_Departement" checkSymetry="YES_ERROR" />
      <relationNNType id="rNN_Pays_DepartementsLimitrophes" startType="et_Pays" endType="et_Departement" />
    </relationNNTypeList>
  </typeDefinitions>

  <elementList>
    <!--Provinces-->
    <element id="el_Estuaire" sortKey="1" type="et_Province" minLevel="0" >
      <elementName>
        <name language="fr" text="Estuaire"/>
        <name language="en" text="Estuaire"/>
      </elementName>
      <attributeList>
        <attribute type="at_Nom1">
          <value language="fr" value="L'Estuaire"/>
          <value language="en" value="Estuaire"/>
        </attribute>
        <attribute type="at_Nom2">
          <value language="fr" value="de l'Estuaire"/>
          <value language="en" value="Estuaire"/>
        </attribute>
        <attribute type="at_Numero">
          <value language="fr" value="1"/>
          <value language="en" value="1"/>
        </attribute>
      </attributeList>
      <numericalAttributeList>
        <numericalAttribute type="nt_Longitude" value="10"/>
        <numericalAttribute type="nt_Latitude" value="0.25"/>
      </numericalAttributeList>
      <relationList>
        <relation type="r11_Province_ChefLieu" linkedElement="el_Libreville"/>
        <relation type="rNN_Province_ProvincesLimitrophes" linkedElement="el_MoyenOgooue"/>
        <relation type="rNN_Province_ProvincesLimitrophes" linkedElement="el_OgooueMaritime"/>
        <relation type="rNN_Province_ProvincesLimitrophes" linkedElement="el_WoleuNtem"/>
      </relationList>
    </element>
    <element id="el_HautOgooue" sortKey="2" type="et_Province" minLevel="0" >
      <elementName>
        <name language="fr" text="Haut-Ogooué"/>
        <name language="en" text="Haut-Ogooué"/>
      </elementName>
      <attributeList>
        <attribute type="at_Nom1">
          <value language="fr" value="Le Haut-Ogooué"/>
          <value language="en" value="Haut-Ogooué"/>
        </attribute>
        <attribute type="at_Nom2">
          <value language="fr" value="du Haut-Ogooué"/>
          <value language="en" value="Haut-Ogooué"/>
        </attribute>
        <attribute type="at_Numero">
          <value language="fr" value="2"/>
          <value language="en" value="2"/>
        </attribute>
      </attributeList>
      <numericalAttributeList>
        <numericalAttribute type="nt_Longitude" value="13.8"/>
        <numericalAttribute type="nt_Latitude" value="-1.3"/>
      </numericalAttributeList>
      <relationList>
        <relation type="r11_Province_ChefLieu" linkedElement="el_Franceville"/>
        <relation type="rNN_Province_ProvincesLimitrophes" linkedElement="el_OgooueLolo"/>
        <relation type="rNN_Province_ProvincesLimitrophes" linkedElement="el_OgooueIvindo"/>
      </relationList>
    </element>
    <element id="el_MoyenOgooue" sortKey="3" type="et_Province" minLevel="0" >
      <elementName>
        <name language="fr" text="Moyen-Ogooué"/>
        <name language="en" text="Moyen-Ogooué"/>
      </elementName>
      <attributeList>
        <attribute type="at_Nom1">
          <value language="fr" value="Le Moyen-Ogooué"/>
          <value language="en" value="Moyen-Ogooué"/>
        </attribute>
        <attribute type="at_Nom2">
          <value language="fr" value="du Moyen-Ogooué"/>
          <value language="en" value="Moyen-Ogooué"/>
        </attribute>
        <attribute type="at_Numero">
          <value language="fr" value="3"/>
          <value language="en" value="3"/>
        </attribute>
      </attributeList>
      <numericalAttributeList>
        <numericalAttribute type="nt_Longitude" value="10.55"/>
        <numericalAttribute type="nt_Latitude" value="-0.35"/>
      </numericalAttributeList>
      <relationList>
        <relation type="r11_Province_ChefLieu" linkedElement="el_Lambarene"/>
        <relation type="rNN_Province_ProvincesLimitrophes" linkedElement="el_Estuaire"/>
        <relation type="rNN_Province_ProvincesLimitrophes" linkedElement="el_Ngounie"/>
        <relation type="rNN_Province_ProvincesLimitrophes" linkedElement="el_OgooueIvindo"/>
        <relation type="rNN_Province_ProvincesLimitrophes" linkedElement="el_OgooueMaritime"/>
        <relation type="rNN_Province_ProvincesLimitrophes" linkedElement="el_WoleuNtem"/>
      </relationList>
    </element>
    <element id="el_Ngounie" sortKey="4" type="et_Province" minLevel="0" >
      <elementName>
        <name language="fr" text="Ngounié"/>
        <name language="en" text="Ngounié"/>
      </elementName>
      <attributeList>
        <attribute type="at_Nom1">
          <value language="fr" value="La Ngounié"/>
          <value language="en" value="Ngounié"/>
        </attribute>
        <attribute type="at_Nom2">
          <value language="fr" value="de la Ngounié"/>
          <value language="en" value="Ngounié"/>
        </attribute>
        <attribute type="at_Numero">
          <value language="fr" value="4"/>
          <value language="en" value="4"/>
        </attribute>
      </attributeList>
      <numericalAttributeList>
        <numericalAttribute type="nt_Longitude" value="11.25"/>
        <numericalAttribute type="nt_Latitude" value="-1.65"/>
      </numericalAttributeList>
      <relationList>
        <relation type="r11_Province_ChefLieu" linkedElement="el_Mouila"/>
        <relation type="rNN_Province_ProvincesLimitrophes" linkedElement="el_MoyenOgooue"/>
        <relation type="rNN_Province_ProvincesLimitrophes" linkedElement="el_OgooueLolo"/>
        <relation type="rNN_Province_ProvincesLimitrophes" linkedElement="el_Nyanga"/>
        <relation type="rNN_Province_ProvincesLimitrophes" linkedElement="el_OgooueMaritime"/>
      </relationList>
    </element>
    <element id="el_Nyanga" sortKey="5" type="et_Province" minLevel="0" >
      <elementName>
        <name language="fr" text="Nyanga"/>
        <name language="en" text="Nyanga"/>
      </elementName>
      <attributeList>
        <attribute type="at_Nom1">
          <value language="fr" value="La Nyanga"/>
          <value language="en" value="Nyanga"/>
        </attribute>
        <attribute type="at_Nom2">
          <value language="fr" value="de la Nyanga"/>
          <value language="en" value="Nyanga"/>
        </attribute>
        <attribute type="at_Numero">
          <value language="fr" value="5"/>
          <value language="en" value="5"/>
        </attribute>
      </attributeList>
      <numericalAttributeList>
        <numericalAttribute type="nt_Longitude" value="11.05"/>
        <numericalAttribute type="nt_Latitude" value="-3.05"/>
      </numericalAttributeList>
      <relationList>
